### PR TITLE
Rebase on top of v1.3.36.111

### PR DESCRIPTION
**Pull request by mherrmann**
Tested to compile with:

 * Visual Studio 2017
 * Windows SDK 10.0.18362.0
 * WTL 10.0.10320
 * Python 2.7
 * pywin32 224
 * SCons 1.3.1
 * Google Software Construction Toolkit 0.9.1
 * Go 1.14.6 (64 bit)
 * Google Protocol Buffers 3.17.3

The remaining dependencies are now included via a `DEPS` file.

The following 43 tests fail. These tests already failed before the rebase, with the exception of `UnitTestHelpersTest.ClearGroupPolicies`, which also fails upstream.

<details>
<summary>See failing tests</summary>

 01. ExtractorTest.EmbedExtract
 02. ExtractorTest.EmbedAppendExtract
 03. ExtractorTest.AlreadyTaggedError
 04. TimeTest.RFC822TimeParsing
 05. UserRightsTest.UserIsLoggedOnInteractively
 06. UtilsTest.ReadEntireFile
 07. UtilsTest.IsUserLoggedOn
 08. UtilsTest.AddAllowedAce
 09. PingTest.BuildOmahaPing
 00. PingTest.SendInProcess
 11. PingTest.PersistAndSendPersistedPings
 12. ScheduledTaskUtilsTest.GoopdateTasks
 13. WebServicesClientTest.Send
 14. WebServicesClientTest.SendForcingHttps
 15. WebServicesClientTest.SendWithCustomHeader
 16. WebServicesClientTest.SendStringWithCustomHeader
 17. DownloadManagerUserTest.DownloadApp_MultiplePackagesInOneApp
 18. InstallManagerInstallAppMachineTest.InstallApp_MsiInstallerSucceeds
 19. InstallManagerInstallAppMachineTest.InstallApp_MsiInstallerWithArgumentSucceeds
 20. InstallerWrapperMachineTest.InstallApp_MsiInstallerSucceeds
 21. InstallerWrapperMachineTest.InstallApp_MsiInstallerWithArgumentSucceeds
 22. WorkerWithTwoAppsTest.CheckForUpdateAsync_Large
 23. WorkerWithTwoAppsTest.DownloadAsyncThenDownloadAndInstallAsync_Large
 24. CupEcdsaRequestTest.PostSimpleRequest
 25. CupEcdsaRequestTest.PostSimpleRequestHttps
 26. NetworkRequestTest.MultipleRequests
 27. GoogleUpdateRecoveryTest.FixGoogleUpdate_FileReturned_Machine
 28. GoogleUpdateRecoveryTest.FixGoogleUpdate_FileReturned_User
 29. GoogleUpdateRecoveryTest.FixGoogleUpdate_FileCollision
 30. GoogleUpdateRecoveryTest.VerifyFileSignature_NotSigned
 31. GoogleUpdateRecoveryTest.VerifyRepairFileMarkup_InvalidMarkups
 32. GoogleUpdateRecoveryTest.ProductionServerResponseTest
 33. SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess
 34. SetupMachineTest.StopGoogleUpdateAndWait_ProcessesDoNotStop
 35. SetupMachineTest.StopGoogleUpdateAndWait_UserHandoffWorkerRunningAsSystem
 36. SetupMachineTest.StopGoogleUpdateAndWait_UserLegacyInstallGoogleUpdateWorkerRunningAsSystem
 37. SetupMachineTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess
 38. UnitTestHelpersTest.ClearGroupPolicies
 39. IsForeground/WebServicesClientTest.SendUsingCup/0
 40. IsForeground/WebServicesClientTest.SendUsingCup/1
 41. IsForeground/WebServicesClientTest.SendString/0
 42. IsForeground/WebServicesClientTest.SendString/1
 43. IsMachine/InstallManagerTest.InstallDir_ReadOnlyFiles/1

</details>

### CODE REVIEW

**Comment by mherrmann** [comment]
(Edit: @mihaiplesa said he's looking into setting up the different build VM so no need for you to do this @linhkikuchi.)

@linhkikuchi compiling this PR requires a slightly different build environment from the current Omaha build. Specifically, instead of `C:\protobuf-2020-sep-rebase`, we need `C:\protobuf-3.17.3` with contents `bin/`, `include/` and `src/` as explained under "Google Protocol Buffers" [here](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/doc/DeveloperSetupGuide.md). Can you help with this?

The repository also now needs to be checked out with the `--recursive` flag to `git clone`. Is there something special I need to do to make this happen @linhkikuchi?

**Comment by mherrmann** [comment]
@simonhong thank you again for the explanations on Slack. I have another question please: Why are the UUIDs for `IPolicyStatus` and `PolicyStatusClass` in [omaha3_idl.idl](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/omaha/goopdate/omaha3_idl.idl) still at Google's defaults? I generated new values now because [CustomizingOmaha](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/doc/CustomizingOmaha.md) says to "generate new GUIDs for every interface and coclass". But maybe there is a reason why they were left unchanged?

**Comment by mherrmann** [comment]
For reviewers: The diff between this PR and `main` is huge because it contains Brave's customizations, some of my changes _and_ all upstream changes since the last rebase. I created this PR by manually re-applying Brave's changes on top of `v1.3.36.111`. The following script illustrates this:

```
git clone git@github.com:brave/omaha
cd omaha
git remote add upstream git@github.com:google/omaha
git fetch upstream
git checkout -b rebase-v1.3.36.111 v1.3.36.111

set .gitattributes to:

    *.reg diff
    *.rc diff
    *.adm diff

git diff f3558c7a..main | git apply --reject
```

So I computed the diff between `f3558c7a`, which is the upstream revision on which the last rebase was based, and Brave's current `main`. Then I applied this diff on top of upstream `v1.3.36.111`. This left ~10 merge failures, which I applied by hand. I then read through all code changes to make sure they are still sound, making some improvements as necessary. I also read through Google's upstream commits since our last rebase, to see if there is anything that is likely to break for us. The most direct interaction point I could find is that Omaha now includes some changes that are shown in Chrome on chrome://policy.

Instead of "merging" this PR in the classical sense, it might be easiest to simply make it the new `main` branch. This is what @mihaiplesa did for the last rebase.

**Comment by mherrmann** [comment]
TODO purely from a code perspective:

- [x] [Copy the updated Omaha IDL file into brave-core and re-generate associated files](https://github.com/brave/omaha/pull/36#issuecomment-960329898) -> done in https://github.com/brave/brave-core/pull/10883.
- [x] Investigate whether omaha/hammer-brave.bat can be removed (appears likely given #35).
- [x] Investigate whether omaha/clickonce/ can be removed.

Once CI can be run for this PR, it should be relatively trivial to remove the files and see whether everything still works. For now, I'm blocked on this CI integration and am waiting for answers to my questions above.

**Comment by simonhong** [comment]
> @simonhong thank you again for the explanations on Slack. I have another question please: Why are the UUIDs for `IPolicyStatus` and `PolicyStatusClass` in [omaha3_idl.idl](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/omaha/goopdate/omaha3_idl.idl) still at Google's defaults? I generated new values now because [CustomizingOmaha](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/doc/CustomizingOmaha.md) says to "generate new GUIDs for every interface and coclass". But maybe there is a reason why they were left unchanged?

I assume above two didn't exist when we forked omaha at first time.
And, I applied previous commits when I did previous rebase w/o checking newly added UUIDs.
Thanks for catching!

and I found that we are using outdated https://github.com/brave/brave-core/blob/master/chromium_src/google_update/google_update_idl.idl.
https://github.com/chromium/chromium/blob/master/google_update/google_update_idl.idl is upstream's latest one and
it includes above new interfaces that our one doesn't have. We should update this idl file also in brave-core by copying generated idl from omaha.

**Comment by mherrmann** [comment]
> We should update this idl file also in brave-core by copying generated idl from omaha.

Good catch. I remember copying the `.idl` from Omaha into Chromium's source tree gives a warning "idl file has changed. Here's how to re-generate some sources that depend on it: ...". I'll look into this.

**Comment by simonhong** [comment]
> > We should update this idl file also in brave-core by copying generated idl from omaha.
> 
> Good catch. I remember copying the `.idl` from Omaha into Chromium's source tree gives a warning "idl file has changed. Here's how to re-generate some sources that depend on it: ...". I'll look into this.

I wrote about it when I did porting first time to https://github.com/brave/brave-browser/wiki/Chromium-rebases at `MIDL issue on Windows` section.
During the build, it'll catch idl file changes by comparing pre-generated files.
Then, we can copy newly generated files to `brave/win_build_output/midl/google_update/`

**Comment by linhkikuchi** [comment]
> protobuf



> (Edit: @mihaiplesa said he's looking into setting up the different build VM so no need for you to do this @linhkikuchi.)
> 
> @linhkikuchi compiling this PR requires a slightly different build environment from the current Omaha build. Specifically, instead of `C:\protobuf-2020-sep-rebase`, we need `C:\protobuf-3.17.3` with contents `bin/`, `include/` and `src/` as explained under "Google Protocol Buffers" [here](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/doc/DeveloperSetupGuide.md). Can you help with this?
> 
> The repository also now needs to be checked out with the `--recursive` flag to `git clone`. Is there something special I need to do to make this happen @linhkikuchi?

@mherrmann so you need me to update the windows build node to have `C:\protobuf-3.17.3`, right?

**Comment by mherrmann** [comment]
@linhkikuchi yes, thank you :-)

**Comment by mherrmann** [comment]
(PS @linhkikuchi as I mentioned Mihai told me yesterday he's looking into this but either he or you may do it; Also, we probably still need the `C:\protobuf-2020-sep-rebase` directory until the new Omaha build is on all channels.)

**Comment by linhkikuchi** [comment]
@mherrmann I downloaded `protoc-3.17.3-win64.zip` from here https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3, but it only has `bin` and `include` folder. Is this the correct one?
```
PS C:\protobuf-3.17.3> ls                                                                                                             
                                                                                                                                      
                                                                                                                                      
    Directory: C:\protobuf-3.17.3                                                                                                     
                                                                                                                                      
                                                                                                                                      
Mode                LastWriteTime         Length Name                                                                                 
----                -------------         ------ ----                                                                                 
d-----        11/4/2021  11:16 AM                bin                                                                                  
d-----        11/4/2021  11:16 AM                include                                                                              
-a----         6/8/2021   2:11 PM            724 readme.txt
PS C:\protobuf-3.17.3> .\bin\protoc.exe --version                                                                                     
libprotoc 3.17.3
```

**Comment by mherrmann** [comment]
@linhkikuchi as I wrote above - we need C:\protobuf-3.17.3 with contents bin/, include/ and src/ as explained under "Google Protocol Buffers" [here](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/doc/DeveloperSetupGuide.md). Thanks!

**Comment by mihaiplesa** [comment]
@linhkikuchi we can install `bin` from `choco` if the path is good for us https://community.chocolatey.org/packages/protoc

Otherwise https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protobuf-all-3.17.3.zip

**Comment by linhkikuchi** [comment]
> @linhkikuchi as I wrote above - we need C:\protobuf-3.17.3 with contents bin/, include/ and src/ as explained under "Google Protocol Buffers" [here](https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/doc/DeveloperSetupGuide.md). Thanks!

@mherrmann this has been done https://github.com/brave/devops/pull/6210

**Comment by mherrmann** [comment]
Thank you @linhkikuchi! I kicked off a build in https://github.com/brave/brave-core/pull/10883 now.

**Comment by mihaiplesa** [comment]
Closing as this PR is not needed anymore since it became the default branch.

**Pull request closed without merging**
