### PR TITLE
WIP: Rebase omaha

### PR DESCRIPTION
**Pull request by simonhong**
I think this branch should become master after renaming current master.
Rebased branch can't be merged onto master.

### CODE REVIEW

**Comment by emerick** [comment]
Looks like there are a lot of conflicts, but I take it those won't be relevant if we're just going to make this the new master?

cc: @mbacchi and @mihaiplesa, just FYI - but assuming you already know this is coming...

**Comment by mbacchi** [comment]
I was not aware of this effort. I wonder if we need to coordinate this with the omaha-server rebase as we're behind there too, and have an open issue to rebase but no plan to do it in the near term: https://github.com/brave/devops/issues/1092

**Comment by simonhong** [comment]
@mbacchi ~~I think this rebase doesn't need omaha-server rebase.~~
Rebased omaha updater doesn't work with current server. https://github.com/brave/brave-browser/issues/5186#issuecomment-513094423

**Comment by simonhong** [comment]
> Looks like there are a lot of conflicts, but I take it those won't be relevant if we're just going to make this the new master?

Yes, it will not have any problem if this becomes master.

**Comment by emerick** [comment]
> Rebased omaha updater doesn't work with current server. [brave/brave-browser#5186 (comment)](https://github.com/brave/brave-browser/issues/5186#issuecomment-513094423)

How does that impact this PR? It seems like we would want to update either both (client and server) or neither, I think.

**Comment by simonhong** [comment]
@emerick yes, both side should be updated. So, this PR should be pended till we can start to debug together on updater client and server.
One more important thing is omaha server that we forked is not maintained by google.
So, latest omaha server impls  could not work with latest google's omaha update client.
We have to deal with it also.

**Comment by simonhong** [comment]
Closed as https://github.com/brave/omaha/pull/29 is opened.

**Pull request closed without merging**
